
# This file defines project settings.
# It's used when running supabase cli commands.
# Reference: https://supabase.com/docs/guides/cli

project_id = "xucpujttrmcfnxalnuzr"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "https://xucpujttrmcfnxalnuzr.supabase.co"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "https://lovable.dev"
additional_redirect_urls = ["https://lovable.app", "https://lovable.dev", "http://localhost:5173", "http://localhost:3000", "http://localhost:5173/login", "http://localhost:3000/login"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = true
enable_confirmations = true

[auth.external.github]
enabled = false
client_id = ""
secret = ""
