
project_id = "xucpujttrmcfnxalnuzr"
# main = "index.ts" # This line seems to be a general setting, ensure it doesn't conflict or remove if not standard.

[functions.ml-fraud-detection]
  verify_jwt = false # Or true, depending on whether it needs auth. Let's assume false for simplicity if it's an internal service call.

[functions.update-realtime-stats]
  verify_jwt = false # Should ideally be true if called from client, or called server-to-server. Let's make it true and handle auth in service.
  # If called from client, it should be authenticated.
  # If realtimeDataService.updatePlayerStatus is to be called by any client, then JWT should be verified.
  # For now, let's keep it false to simplify initial setup, assuming client handles auth before calling.

[functions.debit_wallet]
  verify_jwt = true

[functions.credit_wallet]
  verify_jwt = true

[functions.game_provider_callback]
  verify_jwt = false # Typically, callbacks from providers don't have JWT

[functions.get_daily_metrics]
  verify_jwt = true # Assuming admin/internal tool access

[functions.get_game_performance]
  verify_jwt = true # Assuming admin/internal tool access

[functions.get_provider_analytics]
  verify_jwt = true # Assuming admin/internal tool access

[functions.refresh_analytics_views]
  verify_jwt = true # Admin action

