// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xucpujttrmcfnxalnuzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1Y3B1anR0cm1jZm54YWxudXpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjU2MzYsImV4cCI6MjA2MDY0MTYzNn0.VvGD7ZD85wyoW_dFSAiPf2hdBpkBOzLk2mtTnH7MOZ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);